- client/src/components/Catalog/Tabs/Pictures.tsx
- client/src/components/SingleProject/ProjectMiniModal.tsx
- client/src/redux/actions/projectActions.ts
> image carousel now using catalog Item images

- client/src/components/Dashboard/DashboardPageLower/DashboardNav.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/style/allProjects.scss
- client/src/components/SingleProject/AllProjectView.tsx
- client/src/components/SingleProject/Projects.tsx
- client/src/components/SingleProject/style/_projectView.scss
- server/src/controller/projectController.ts
added toggle for archive / active on projects, and fixed a hang up on editing projects.
> Projects toggle

- client/src/components/SingleProject/ProjectAttachments.tsx
> safari fix

- client/src/components/Dashboard/DashboardPageLower/DashboardNav.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/AllProjectsTable.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/ProjectMiniModal.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/ViewModal.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/style/_projectModal.scss
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/style/allProjects.scss
- client/src/components/SingleProject/AllProjectView.tsx
- client/src/components/SingleProject/ModalAttachments.tsx.tsx
- client/src/components/SingleProject/ProjectMiniModal.tsx
- client/src/redux/actions/projectActions.ts
- server/src/controller/projectAttchmentController.ts
Can probably close last PR, this was built with same commit history. Updated some styling, added some new functionality.
> Modal r only

- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/ProjectMiniModal.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/ViewModal.tsx
- client/src/components/SingleProject/AllProjectView.tsx
- client/src/components/SingleProject/ModalAttachments.tsx.tsx
- client/src/components/SingleProject/ProjectMiniModal.tsx
- client/src/redux/actions/projectActions.ts
- server/src/controller/projectAttchmentController.ts
Updates rendering on deleting projects, and the duplicating button now functions on each table for any project.
> Dup delete

- client/src/api/axios.ts
- client/src/components/Inventory/Inventory.tsx
- client/src/components/Inventory/styles/inventory.scss
- client/src/components/SingleProject/AllProjectView.tsx
- server/nodemon.json
- server/server.ts
- server/src/controller/catalogController.ts
- server/src/middleware/s3.ts
- server/src/routes/employeeRoutes.ts
> Edit catalog

- client/src/api/axios.ts
- client/src/app/typescriptTypes.ts
- client/src/components/PersistLogin/PersistLogin.tsx
- client/src/redux/actions/authActions.ts
- client/src/redux/reducers/authSlice.ts
> token to state

- client/src/api/axios.ts
- server/src/controller/projectController.ts
> maybe this will work

- client/src/components/Login/Login.tsx
- server/src/routes/publicRoutes.ts
> GOD IS DEAD

- client/src/components/AdminDashboard/UsersTable.tsx
The project needs to be more descriptive on what its doing so documentation has been added.
> added documentation for use effect in users table

- client/src/components/AdminDashboard/CreateUserModal.tsx
- client/src/components/AdminDashboard/styles/CreateUserModal.scss
Reverts Banyan-Labs/CiannaLighting#172
> Revert "add copy password text and tooltip"

- package.json
- server/src/controller/userController.ts
- server/src/model/User.ts
- server/src/routes/adminRoutes.ts
added `isActive` field to the user model and set the default value to true for new user
created endpoint to add an `isActive` field to all existing users in deployed environments
> adding is active column to user table

- client/src/components/AdminDashboard/UsersTable.tsx
- client/src/components/AllUserProjects/AllUserProjects.tsx
- client/src/components/SingleProject/AllProjectView.tsx
> users sorting

- client/src/components/AdminDashboard/CreateUserModal.tsx
- client/src/components/AdminDashboard/styles/CreateUserModal.scss
added a button icon to copy generated password to the end user clipboard.
included a tooltip to show the success
bonus added tooltip for generating password button too
> CIANA-165: add featrue copy password text to clipboard and tooltip

- client/src/components/Modal/Modal.tsx
- client/src/components/Rooms/RoomDetails.tsx
- client/src/redux/actions/projectActions.ts
> create project working

- client/src/components/Inventory/Inventory.tsx
Catalog Indexing handled with customized form requirements.
> Indexing handled with customized for requirements

- client/src/components/Modal/Modal.tsx
- client/src/components/Rooms/LightSide/CatalogItem.tsx
- client/src/components/Rooms/LightSide/DeleteModal.tsx
- client/src/redux/actions/projectActions.ts
- server/src/controller/rfpController.ts
- server/src/interfaces/rfpDocInterface.ts
- server/src/model/ProposalTableRow.ts
- server/src/routes/userRoutes.ts
Edit actions for room names and project names functioning, TYPE: any in rfp controller in map was necessary to save documents upon editing.
> editing rooms and projects functioning through proposals

- client/package.json
- client/src/components/Catalog/Tabs/Pictures.tsx
- client/src/components/Rooms/LightSide/CatalogItem.tsx
- client/src/components/Rooms/LightSide/LightCarousel.tsx
- client/src/components/Rooms/LightSide/LightDetails.tsx
- client/src/components/Rooms/LightSide/carousel.style.scss
- client/src/components/Rooms/RoomDetails.tsx
Created carousel component for lights and fix bootstrap util classes
> light carousel and styling

- client/src/components/Inventory/Inventory.tsx
> 172 removed add button

- client/src/components/Rooms/LightSide/LightCarousel.tsx
- client/src/components/Rooms/LightSide/carousel.style.scss
- client/src/components/commons/ModalBase/modalBase.scss
> CIANA-174:  add fullscreen modal to light carousel

- client/src/components/Catalog/Tabs/Options.tsx
- client/src/components/Catalog/Tabs/Tabs.tsx
- server/src/controller/catalogController.ts
- server/src/controller/rfpController.ts
The attachments should be removing on their own when something changes, filename names working properly, and header updating properly
> Attach filename header

- server/src/controller/activityController.ts
> 🐛 FIX: worked 2 weeks ago

- docker-compose.yml
install docker to host machine and update the kernel
> 📦 NEW: added docker compose file

- client/src/components/Catalog/Tabs/Tabs.tsx
- client/src/components/Inventory/Inventory.tsx
- server/src/controller/userController.ts
Reverts Banyan-Labs/CiannaLighting#230
> Revert "bug fix"

- client/src/components/AdminDashboard/AdminDashboard.tsx
This reverts commit 786d521f6ff26c93c48404b619ff0694fc11c0eb.
> Revert "reset-db"

- client/src/components/AdminDashboard/AdminDashboard.tsx
This reverts commit 31b39fc2e8f596574c39a2587591447571b2810c.
> Revert "Revert "reset-db""

- client/src/components/AdminDashboard/CreateUserModal.tsx
- client/src/components/Dashboard/DashboardPageLower/DashboardSubComponents/AllProjectsTable.tsx
- client/src/components/Inventory/Inventory.tsx
- client/src/components/Layout/AlertModal.tsx
- client/src/components/Layout/Layout.tsx
- client/src/components/Layout/style/alertModal.scss
- client/src/components/Rooms/RoomDetails.tsx
- client/src/components/SingleProject/AllProjectView.tsx
- client/src/components/SingleProject/ProjectPageLower/ProjectSubComponents/AllRooms/IdRooms.tsx
- client/src/components/SingleProject/ProjectSummary.tsx
- client/src/redux/reducers/modalSlice.ts
- client/src/redux/store.ts
Created a new branch BLMS-1601-2 with correct formatting to replace BLMS-1601.  Created modal messages and implemented them in place of alert messages.  Removed all alert messages.
> BLMS-1601-2 Created modal confirmations and removed alert messages

- client/src/components/Dashboard/YourProjects/YourProjects.tsx
Centered all project tiles on dashboard.
> BLMS-1618, centered project tiles on dashboard

- client/src/components/Dashboard/style/dashboard.scss
Changed Folder Icon from 40px to 20px per discussion with Eric
> BLMS-1617 CIANA - UI - Dashboard header tweak

- client/src/components/Dashboard/style/dashboard.scss
Changed Folder Icon size to 30px
> BLMS-1617 Dashboard header tweak
